serverAddr = "{FRP_SERVER_HOST}"
serverPort = {FRP_SERVER_PORT}

[auth]
token = "{FRP_TOKEN}"

[[visitors]]
name = "harbor-xtcp"
type = "xtcp"
serverName = "{FRP_SERVER_NAME}"
secretKey = "{FRP_SECRET_KEY}"
bindAddr = "0.0.0.0"
bindPort = {FRP_LISTEN_PORT}
keepTunnelOpen = true
