name: main

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  FRP_SERVER_HOST: "${{ secrets.FRP_SERVER_HOST }}"
  FRP_SERVER_PORT: "${{ secrets.FRP_SERVER_PORT }}"
  FRP_TOKEN: "${{ secrets.FRP_TOKEN }}"
  FRP_SERVER_NAME: "${{ secrets.FRP_SERVER_NAME }}"
  FRP_SECRET_KEY: "${{ secrets.FRP_SECRET_KEY }}"
  FRP_LISTEN_PORT: "${{ secrets.FRP_LISTEN_PORT }}"
  NAMESPACE: "${{ secrets.NAMESPACE }}"
  USERNAME: "${{ secrets.USERNAME }}"
  PASSWORD: "${{ secrets.PASSWORD }}"

jobs:
  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    # 增加可用磁盘空间
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:

        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        # 如果空间还是不够用，可以把以下开启，清理出更多空间
        remove-android: 'true'
        remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Start Frp
      run: |
        sed -i "s/{FRP_SERVER_HOST}/${FRP_SERVER_HOST}/g" frp/frpc.toml
        sed -i "s/{FRP_SERVER_PORT}/${FRP_SERVER_PORT}/g" frp/frpc.toml
        sed -i "s/{FRP_TOKEN}/${FRP_TOKEN}/g" frp/frpc.toml
        sed -i "s/{FRP_SERVER_NAME}/${FRP_SERVER_NAME}/g" frp/frpc.toml
        sed -i "s/{FRP_SECRET_KEY}/${FRP_SECRET_KEY}/g" frp/frpc.toml
        sed -i "s/{FRP_LISTEN_PORT}/${FRP_LISTEN_PORT}/g" frp/frpc.toml
        chmod +x frp/frpc
        frp/frpc -c frp/frpc.toml > /dev/null &
    - name: Setting Docker
      run: |
        sudo echo "{ \"exec-opts\": [\"native.cgroupdriver=cgroupfs\"], \"cgroup-parent\": \"/actions_job\", \"insecure-registries\": [\"127.0.0.1:${FRP_LISTEN_PORT}\"] }" > ~/.docker/daemon.json
        sudo service docker restart
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login Docker
      run: docker login -u $USERNAME -p $PASSWORD 127.0.0.1:${FRP_LISTEN_PORT}

